--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comments (
    id bigint NOT NULL,
    message character varying(255),
    rating double precision,
    game_description_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.comments OWNER TO postgres;

--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: game_descriptions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.game_descriptions (
    id bigint NOT NULL,
    age_limit integer NOT NULL,
    description character varying(3000) NOT NULL,
    genre character varying(255) NOT NULL,
    image_name character varying(255),
    image_path character varying(255),
    image_type character varying(255),
    name character varying(255) NOT NULL,
    platform character varying(255) NOT NULL,
    published_at integer NOT NULL,
    publisher character varying(255) NOT NULL,
    user_id bigint
);


ALTER TABLE public.game_descriptions OWNER TO postgres;

--
-- Name: game_descriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.game_descriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_descriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_token (
    id bigint NOT NULL,
    expiry_date timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.refresh_token OWNER TO postgres;

--
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.user_roles OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    birth_date date,
    created_at timestamp(6) without time zone,
    email character varying(255),
    password character varying(255),
    username character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: comments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.comments (id, message, rating, game_description_id, user_id) FROM stdin;
\.


--
-- Data for Name: game_descriptions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.game_descriptions (id, age_limit, description, genre, image_name, image_path, image_type, name, platform, published_at, publisher, user_id) FROM stdin;
1	16	This is a test description.	Action	GaDEscKvitgls62gkxvid1.jpg	C:/apache-tomcat-9.0.39/webapps/ROOT/images/GaDEscKvitgls62gkxvid1.jpg	multipart/form-data	Example Game	PC	2023	Example Publisher	6
6	12	Ez egy nagyon jó játék! Próbáld ki te is!	szimuláció	blob	C:/apache-tomcat-9.0.39/webapps/ROOT/images/blob	image/jpg	The Sims 4	pc,xbox,ps5	2014	Electronic Arts	6
\.


--
-- Data for Name: refresh_token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.refresh_token (id, expiry_date, token, user_id) FROM stdin;
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, name) FROM stdin;
1	ADMIN
2	USER
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_roles (user_id, role_id) FROM stdin;
1	2
2	2
3	2
4	2
5	2
6	2
7	2
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, birth_date, created_at, email, password, username) FROM stdin;
1	2003-04-29	2025-01-15 13:41:44.234691	bbecca1212@gmail.com	$2a$10$TLcJIhRTLqn2lmw.VAVR2u1VAkrsN7kz3fUSSgu7tlJRFETP0nSOW	BBecca123
2	2003-04-29	2025-01-15 13:49:53.778886	bodarebeka123@gmail.com	$2a$10$X8J6/wOVqaXC0VntuPK/K.1CkJPk9SHZxM4Uj1vhF36JjoUgY2VzG	BBecca35
3	2000-02-06	2025-01-15 15:12:11.910775	berni06@gmail.com	$2a$10$/xL3fM6DFwTvVJy0wTs86eGVhBAoYN02QL10XXqUOMjGfiT6fjc/e	Berni06
4	1986-02-21	2025-01-16 11:43:11.313117	blablabla@gmail.com	$2a$10$aOk4DsB5XxtxJ3mARE62WuM/bFBLxdRdvEFoFb1gdeNfbpgjqHKfa	RebiBaba
5	1994-12-15	2025-01-16 12:45:32.020404	rebibaba@gmail.com	$2a$10$nplLDnMV5kdjVkRJk74MMewEcYk3uF/ll2rW7eI986tXpP7yzdO1S	RebiBaba123
6	2003-04-29	2025-01-17 13:04:47.884124	rebuska12@gmail.com	$2a$10$ZUKtt7xoTbSq/4FxGZZMFee0WHm0xFxBgY38ctExMB0xHtJYPAULS	Rebuska12
7	2025-01-03	2025-01-22 15:48:23.455407	asder87@gmail.com	$2a$10$7h6A7AH/FVOT8mP4ISXLd.COej7IGBLpwKHSXXLMegiOwc72dbLyK	Asder87
\.


--
-- Name: comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comments_id_seq', 1, false);


--
-- Name: game_descriptions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.game_descriptions_id_seq', 6, true);


--
-- Name: refresh_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.refresh_token_id_seq', 1, false);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 2, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 7, true);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: game_descriptions game_descriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_descriptions
    ADD CONSTRAINT game_descriptions_pkey PRIMARY KEY (id);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: game_descriptions ukfl8qmmfi1cb1siss900ctr4x9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_descriptions
    ADD CONSTRAINT ukfl8qmmfi1cb1siss900ctr4x9 UNIQUE (name);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: refresh_token ukr4k4edos30bx9neoq81mdvwph; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT ukr4k4edos30bx9neoq81mdvwph UNIQUE (token);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: comments fk8omq0tc18jd43bu5tjh6jvraq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fk8omq0tc18jd43bu5tjh6jvraq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: refresh_token fkjtx87i0jvq2svedphegvdwcuy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fkjtx87i0jvq2svedphegvdwcuy FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: game_descriptions fkoyo038uvpajyko49bakeoj8gs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_descriptions
    ADD CONSTRAINT fkoyo038uvpajyko49bakeoj8gs FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: comments fkto8ggpotv5v2pvhr8e21wpu7c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fkto8ggpotv5v2pvhr8e21wpu7c FOREIGN KEY (game_description_id) REFERENCES public.game_descriptions(id);


--
-- PostgreSQL database dump complete
--

