--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bans; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bans (
    id bigint NOT NULL,
    ban_expiration integer NOT NULL,
    banned_at timestamp(6) without time zone,
    expired boolean,
    reason character varying(255),
    user_id bigint
);


ALTER TABLE public.bans OWNER TO postgres;

--
-- Name: bans_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    message character varying(255),
    rating integer,
    game_description_id bigint,
    user_id bigint
);


ALTER TABLE public.comments OWNER TO postgres;

--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: game_descriptions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.game_descriptions (
    id bigint NOT NULL,
    age_limit integer NOT NULL,
    avg_rating integer,
    created_at timestamp(6) without time zone,
    description character varying(3000) NOT NULL,
    genre character varying(255) NOT NULL,
    image_name character varying(255),
    image_path character varying(255),
    image_type character varying(255),
    name character varying(255) NOT NULL,
    platform character varying(255) NOT NULL,
    published_at integer NOT NULL,
    publisher character varying(255) NOT NULL,
    user_id bigint
);


ALTER TABLE public.game_descriptions OWNER TO postgres;

--
-- Name: game_descriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.game_descriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_descriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    birth_date date,
    created_at timestamp(6) without time zone,
    email character varying(255),
    password character varying(255),
    role character varying(255),
    username character varying(255),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'MODERATOR'::character varying, 'USER'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: bans; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bans (id, ban_expiration, banned_at, expired, reason, user_id) FROM stdin;
\.


--
-- Data for Name: comments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.comments (id, created_at, message, rating, game_description_id, user_id) FROM stdin;
1	2025-04-23 17:13:34.287828	asdasdasd	5	7	5
\.


--
-- Data for Name: game_descriptions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.game_descriptions (id, age_limit, avg_rating, created_at, description, genre, image_name, image_path, image_type, name, platform, published_at, publisher, user_id) FROM stdin;
2	3	0	2025-04-22 11:50:25.597874	Integer dignissim pharetra lacus, sit amet luctus lorem tincidunt quis. Phasellus euismod congue nisl. Quisque sit amet velit id nunc sodales facilisis sed fringilla tellus. Sed quis eros eu odio egestas elementum. Pellentesque a eros non eros blandit tristique eu ut sapien. Mauris eu quam eget mauris pulvinar ornare. Curabitur quis libero eu purus sodales pretium. Duis dolor ligula, accumsan id sagittis at, dictum a justo. Donec ipsum magna, sagittis ac tempor vitae, euismod a ex. Morbi rutrum ipsum malesuada finibus laoreet. 	szimuláció	3fcdcefb-1b7e-4cf9-af47-1a2cbfd3f5b1.jpg	C:/apache-tomcat-9.0.39/webapps/ROOT/images/3fcdcefb-1b7e-4cf9-af47-1a2cbfd3f5b1.jpg	image/jpeg	Farming Simulator 22	PC, XBOX, PlayStation	2021	GIANTS Software	5
3	3	0	2025-04-22 11:55:29.527627	Nullam ac dui nunc. In enim orci, semper id lectus vitae, pulvinar tincidunt enim. Vestibulum interdum viverra rutrum. In hac habitasse platea dictumst. Quisque tincidunt, metus tempus venenatis tempor, sem sapien iaculis tortor, in congue eros tortor eget lectus. Maecenas fermentum vehicula elit non malesuada. Duis tempor velit id neque efficitur tincidunt. Proin blandit laoreet lectus. Curabitur molestie ut nibh a fermentum. Etiam porttitor urna libero. Cras convallis urna nec quam consectetur, ac viverra arcu porta. Phasellus blandit massa odio, ut consequat est blandit eu. Donec mauris quam, pulvinar eu augue eget, pharetra convallis felis. Duis nec tincidunt ligula. Etiam non nisi ut nisl laoreet commodo. Nulla ac ipsum vitae urna ultrices sodales id accumsan libero	verseny	feed5729-68a6-4919-bd5a-dcff84d06ee1.jpg	C:/apache-tomcat-9.0.39/webapps/ROOT/images/feed5729-68a6-4919-bd5a-dcff84d06ee1.jpg	image/jpeg	Rocket League	PC, Nintendo, XBOX, PlayStation	2015	Psyonix	6
4	18	0	2025-04-22 12:04:25.877423	Duis consectetur eros volutpat quam lobortis, quis maximus felis fermentum. Quisque pulvinar, ante eget semper placerat, arcu nisi pulvinar mi, et convallis sem enim sed augue. Nam dignissim turpis sit amet neque bibendum, vitae aliquam sapien iaculis. Integer pulvinar justo justo, at accumsan risus fermentum et. Pellentesque ullamcorper elit quis euismod rhoncus. Donec ullamcorper, sem sit amet dignissim dapibus, erat justo suscipit orci, efficitur mattis nibh nisl id sem. In sit amet dolor eget ex fermentum sagittis eget vel velit. Nullam sem nisl, consectetur at ultricies at, pharetra non felis. Praesent viverra eleifend turpis at interdum. Nam venenatis pretium tellus vel dictum. Aenean tristique elementum ante, sed volutpat augue facilisis in. Nullam sit amet augue nec neque varius pharetra. Phasellus rutrum bibendum lorem sit amet gravida. Phasellus id lorem augue. Cras non elit posuere, vehicula nibh vel, interdum libero. 	akció	fe550fae-526f-411a-8545-8102bdf327ee.jpg	C:/apache-tomcat-9.0.39/webapps/ROOT/images/fe550fae-526f-411a-8545-8102bdf327ee.jpg	image/jpeg	The Last of Us Part 1	PC, PlayStation	2022	Naughty Dogs	2
8	16	0	2025-04-23 16:44:17.970641	sdbfgvDSFVFIZSDBFJ	RPG	9b2401ea-5d0e-4a30-990c-97a8b064e661.png	C:/apache-tomcat-9.0.39/webapps/ROOT/images/9b2401ea-5d0e-4a30-990c-97a8b064e661.png	image/png	Mandragora	PC	2025	kiado	8
7	12	5	2025-04-23 11:52:50.870851	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin scelerisque dui sed dapibus cursus. Aenean placerat sapien felis, ut rhoncus risus dignissim at. Vestibulum porta elit enim, ac imperdiet lacus tincidunt quis. Aliquam vestibulum arcu mi, ac volutpat neque malesuada nec. Sed eros felis, congue a neque sit amet, aliquam eleifend ipsum. Cras non eros turpis	szimuláció	\N	\N	\N	The Sims 4	PC, XBOX, PlayStation	2014	Electronic Arts	7
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, birth_date, created_at, email, password, role, username) FROM stdin;
3	2000-02-02	2025-04-06 14:32:17.93873	berni06@gmail.com	$2a$10$V972FWp7m0jNwc5Un2i4k.UJSpVEw2QkitGngCN1M9xNQy6XR7Xtm	USER	Berni06
5	1981-05-05	2025-04-06 14:34:01.802271	boda.tibor80@gmail.com	$2a$10$qqb9MuMiSjKWJj8vqauIZuhcUVIPis3A2AHlMaKBofl.1Ki0ZbQKO	USER	BodaTibor80
6	1993-04-18	2025-04-06 14:35:46.249235	bmagdi43@gmail.com	$2a$10$75DyVB2fsmro.QNPq4KaleOPWsr6gcJpDiryVP.u/YBc.5Fu2MrKK	USER	BMagdi43
4	2004-09-17	2025-04-06 14:33:04.541462	asder87@gmail.com	$2a$10$m/lfT9HdzyrXGZ1FBjKl8O77JMUHN/y7lxPEVBAPRz1qGCvS2VbV6	MODERATOR	Asder87
2	2000-12-12	2025-04-06 14:31:17.149524	rebuska12@gmail.com	$2a$10$Rv/MRrb84JPDJK.Vyx7xBed77vUJhVmRcn46kOc6PxtHONiP/bsdu	MODERATOR	Rebuska12
7	2000-01-01	2025-04-17 14:44:48.559211	admin999@gmail.com	$2a$10$LxJyznqJGXpucoN2mAA0c.2oifFhccVxW9S6KIsrNclaOq7deSbc2	ADMIN	Admin
8	2023-08-05	2025-04-23 16:42:39.513471	bsbs@gmail.com	$2a$10$fU1/lrnpmUDZ7wWT2z74o.iA982Hw/ArZ2BtL9nY7kOF.F8MSdgmW	USER	Bsbs
\.


--
-- Name: bans_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bans_id_seq', 1, false);


--
-- Name: comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comments_id_seq', 1, true);


--
-- Name: game_descriptions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.game_descriptions_id_seq', 8, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 8, true);


--
-- Name: bans bans_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bans
    ADD CONSTRAINT bans_pkey PRIMARY KEY (id);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: game_descriptions game_descriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_descriptions
    ADD CONSTRAINT game_descriptions_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: game_descriptions ukfl8qmmfi1cb1siss900ctr4x9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_descriptions
    ADD CONSTRAINT ukfl8qmmfi1cb1siss900ctr4x9 UNIQUE (name);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: comments fk8omq0tc18jd43bu5tjh6jvraq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fk8omq0tc18jd43bu5tjh6jvraq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: bans fkdshp5tj95xpg7ikybc4teb68q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bans
    ADD CONSTRAINT fkdshp5tj95xpg7ikybc4teb68q FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: game_descriptions fkoyo038uvpajyko49bakeoj8gs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_descriptions
    ADD CONSTRAINT fkoyo038uvpajyko49bakeoj8gs FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: comments fkto8ggpotv5v2pvhr8e21wpu7c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fkto8ggpotv5v2pvhr8e21wpu7c FOREIGN KEY (game_description_id) REFERENCES public.game_descriptions(id);


--
-- PostgreSQL database dump complete
--

